POST /api/v1/auth/register
host: localhost:8080
content-type: application/json

{
  "username": "kildong",
  "password": "mypass1",
  "name": "김길동",
  "email": "kildong@test.com",
  "role": "MANAGER"
}

###
POST /api/v1/auth/authenticate
host: localhost:8080
content-type: application/json

{
  "username": "kildong",
  "password": "mypass1"
}